In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,5,6,7]],np.int64)

In [3]:
myarr

array([[3, 5, 6, 7]], dtype=int64)

In [4]:
myarr[0,1]

5

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,2]=45

In [8]:
myarr

array([[ 3,  5, 45,  7]], dtype=int64)

In [9]:
myarr[0,1]=85

In [10]:
myarr

array([[ 3, 85, 45,  7]], dtype=int64)

## Array creation :Conversion from other Python structure

In [11]:
listarray=np.array([[1,2,3],[5,2,3],[8,9,6]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 2, 3],
       [8, 9, 6]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.size

9

In [15]:
listarray.shape

(3, 3)

In [16]:
np.array({34,85,65})

array({65, 34, 85}, dtype=object)

In [17]:
Zeros=np.zeros((2,5))

In [18]:
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
rng=np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lnspace=np.linspace(1,50,5)

In [22]:
lnspace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [23]:
emp=np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 1.69118108e-306, 6.23060065e-307,
        8.45593934e-307, 7.56593017e-307, 8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306, 1.60220393e-306],
       [1.29060735e-306, 1.11261570e-306, 7.56602523e-307,
        1.29062229e-306, 8.34446835e-308, 1.39071445e-307],
       [1.33511562e-306, 8.90103560e-307, 1.42410974e-306,
        1.00132228e-307, 1.33511018e-306, 1.69119330e-306]])

In [25]:
emp_like=np.empty_like(lnspace)

In [26]:
emp_like

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [27]:
ide=np.identity(5)

In [28]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
ide.shape

(5, 5)

In [30]:
arr=np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr=arr.reshape(3,33)

In [33]:
arr.shape

(3, 33)

In [34]:
x=[[1,2,3],[5,2,3],[8,9,6]]

In [35]:
x

[[1, 2, 3], [5, 2, 3], [8, 9, 6]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [5, 2, 3],
       [8, 9, 6]])

In [38]:
ar.sum(axis=0)

array([14, 13, 12])

In [39]:
ar.sum(axis=1)

array([ 6, 10, 23])

In [40]:
ar.T

array([[1, 5, 8],
       [2, 2, 9],
       [3, 3, 6]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
5
2
3
8
9
6


In [43]:
arr.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
one=np.array([1,23,53,63,2])

In [47]:
one

array([ 1, 23, 53, 63,  2])

In [48]:
one.size


5

In [49]:
one.argmax()

3

In [50]:
one.argmin()

0

In [51]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [5, 2, 3],
       [8, 9, 6]])

In [53]:
ar.argsort()

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [61]:
ar

array([[1, 2, 3],
       [5, 2, 3],
       [8, 9, 6]])

In [62]:
ar.argmax()

7

In [63]:
ar.argmin()

0

In [64]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [65]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [66]:
ar.argmax(axis=1)

array([2, 0, 1], dtype=int64)

In [67]:
ar.argmin(axis=1)

array([0, 1, 2], dtype=int64)

In [68]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [69]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [70]:
ar.ravel()

array([1, 2, 3, 5, 2, 3, 8, 9, 6])

In [71]:
# ar.reshape(9)

array([1, 2, 3, 5, 2, 3, 8, 9, 6])

ValueError: cannot reshape array of size 9 into shape (3,5)

In [73]:
ar2=np.array([[10,20,30],[50,20,35],[80,90,60]])

In [74]:
ar2

array([[10, 20, 30],
       [50, 20, 35],
       [80, 90, 60]])

In [75]:
ar+ar2

array([[11, 22, 33],
       [55, 22, 38],
       [88, 99, 66]])

In [79]:
ar-ar2

array([[ -9, -18, -27],
       [-45, -18, -32],
       [-72, -81, -54]])

In [80]:
ar

array([[1, 2, 3],
       [5, 2, 3],
       [8, 9, 6]])

In [81]:
ar2

array([[10, 20, 30],
       [50, 20, 35],
       [80, 90, 60]])

In [82]:
ar/ar2

array([[0.1       , 0.1       , 0.1       ],
       [0.1       , 0.1       , 0.08571429],
       [0.1       , 0.1       , 0.1       ]])

In [83]:
ar*ar2

array([[ 10,  40,  90],
       [250,  40, 105],
       [640, 810, 360]])

In [84]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 1.41421356, 1.73205081],
       [2.82842712, 3.        , 2.44948974]])

In [85]:
np.sqrt(ar2)

array([[3.16227766, 4.47213595, 5.47722558],
       [7.07106781, 4.47213595, 5.91607978],
       [8.94427191, 9.48683298, 7.74596669]])

In [86]:
ar.sum

<function ndarray.sum>

In [87]:
ar.sum()

39

In [88]:
ar.max()

9

In [89]:
ar.min()

1

In [90]:
np.where(ar>5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [91]:
ar

array([[1, 2, 3],
       [5, 2, 3],
       [8, 9, 6]])

In [92]:
type(np.where(ar>5))

tuple

In [93]:
np.count_nonzero(ar)

9

In [94]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [95]:
ar[1,2]=0

In [96]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [97]:
import sys

In [98]:
ch_ar=[0,4,55,2]

In [99]:
np_ar=np.array(ch_ar)

In [101]:
sys.getsizeof(1)*len(ch_ar)

112

In [103]:
np_ar.itemsize*np_ar.size

16